fail_fast: true

repos:
  - repo: local
    hooks:
      - id: nocommit
        name: Check for `nocommit` instances
        description: Check if any committed files contain the string `nocommit`
        entry: sh -c "! git grep --quiet --ignore-case nocommit -- :/src"
        language: system
        pass_filenames: false
      - id: cargo-test
        name: cargo test
        description: Run cargo test on the committed code
        entry: cargo test
        language: system
        pass_filenames: false
