fail_fast: true

repos:
  - repo: local
    hooks:
      - id: no-empty-files
        name: Check if any files are empty
        description: Check if any committed files are empty
        entry: scripts/empty.sh
        language: script
        pass_filenames: true
        stages: [commit]
      - id: nocommit
        name: Check for `nocommit` instances
        description: Check if any committed files contain the string `nocommit`
        entry: sh -c "! git grep --ignore-case nocommit -- :/src"
        language: system
        pass_filenames: false
        stages: [commit]
      - id: cargo-test
        name: cargo test
        description: Run cargo test on the committed code
        entry: cargo test
        language: system
        types_or: [rust, toml]
        pass_filenames: false
        stages: [push]
      - id: cargo-doc
        name: cargo doc
        description: Ensure that documentation builds correctly
        entry: env RUSTDOCFLAGS="-D warnings" cargo doc
        language: system
        types_or: [rust, toml]
        pass_filenames: false
        stages: [push]
