[package]
name = "huck"
version = "0.1.0"
authors = ["Jesse Adamson Paroz <hucklanguage@gmail.com>"]
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
nom = "7"
log = "0.4"
env_logger = "0.9"
thiserror = "1.0"
