[package]
name = "huck"
version = "0.1.0"
authors = ["Jesse Paroz <jesse.paroz@gmail.com>"]
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
nom = "6"
log = "0.4"
env_logger = "0.9"
