#!/usr/bin/env bash

if git grep --ignore-case --context 3 nocommit -- :/src
then
    echo 'Found an instance of "nocommit", stopping commit!'
    exit 1
fi

# Stash changes so we test against the code to be committed
git stash push --keep-index --include-untracked

cargo test
test_succeeded=$?

git stash pop

if [ $test_succeeded -eq 0 ]
then : # do nothing
else
    status=$?
    echo "Test suite had failures, stopping commit!"
    exit $status
fi

exit 0
